<a href="https://colab.research.google.com/github/meghanaraokanneganti/Machine-learning/blob/main/Pytorch%20Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.0.1+cu118'

In [5]:
scalar = torch.tensor(7);
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
scalar.item()

7

In [11]:
# A vector is a single dimension tensor but can contain many numbers.
#Vector
vector = torch.tensor([3,3]);
print(vector)
vector.ndim

tensor([3, 3])


1

In [12]:
vector.shape

torch.Size([2])

In [17]:
matrix = torch.tensor([[3,3],[7,7]]);
print('size is ' + str(matrix.ndim))
print("shape is "+str(matrix.shape))

size is 2
shape is torch.Size([2, 2])


In [18]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [25]:
print(TENSOR.shape)

torch.Size([1, 3, 3])
<built-in method size of Tensor object at 0x7d4f8654e2a0>


In [31]:
print("size is "+str(TENSOR.ndim))

size is 3


In [32]:
#Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...
#a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.3251, 0.7841, 0.3858, 0.7629],
         [0.1117, 0.5570, 0.4087, 0.0164],
         [0.9268, 0.5897, 0.5673, 0.9911]]),
 torch.float32)

In [33]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [34]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [35]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-35-a09072c806d9>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# Can also create a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])